name: 💫 Epic
description: Use tasklists to split up a larger piece of work into multiple tasklists and multiple subtasks.
title: "[Epic] "

labels:
  - type/epic
  
body:
  - type: textarea
    attributes:
      label: Describe the Epic
      description: |
        A clear and concise description of the epic.
    validations:
      required: true
