name: Feature Request
description: Feature Request
title: "[Feature]: "
labels:
  - feature
projects:
  -
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Feature Request!
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ABB-PAEN/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true