name: Feature Request
description: Feature Request
title: "REPLACE ME"
labels:
  - feature
projects:
  -
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Feature Request!
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      description: feature?
      placeholder: Tell us what feature you want to see!
      value: ""
    validations:
      required: false
