name: 🚀 Feature Request
description: [FEATURE] Feature Request
title: "clear and concise title"
labels:
  - enhancement
  
body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request report!**

  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Remember to add screenshots or images that supports or describes the feature**
        
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
